# Question 1

In [18]:
a = print('Hello World')
a

Hello World


# Question 2

In [5]:
for x in range (10):
    if x < 5:
        print (x)

0
1
2
3
4


# Question 3

In [14]:
x = 100
print('The variable x is ' + str(type(x)) + ' type')

The variable x is <class 'int'> type


In [10]:
float_x = float(x)
print (float_x)
type(float_x)

100.0


float

# Question 4

In [22]:
y = None
print(type(y))

<class 'NoneType'>


# Question 5

In [23]:
x = -0.05
y = 0, 1, 2

print(round(x, 1))

-0.1


# Question 6

In [32]:
name = input('Hello, what is your name? ')
if name == 'Dani' or name == 'Daniel':
    print ('What a horrible name')
else:
    print ('What a beatufull name')
    
age = input('Thank you, and what is your age? ')
age = int(age)
if age >= 35:
    print('You are too old')
else:
    print('Oh, you are in the flower of life')


Hello, what is your name? Edu
What a beatufull name
Thank you, and what is your age? 34
Oh, you are in the flower of life


# Question 7

In [46]:
import numpy as np

x = np.arange (1, 17).reshape(4,4)
print(x)

print()

y = [[1, 23, 4], [5, 67, 8], [9, 1011, 12], [13, 1415, 16]]
y = np.array(y)
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[   1   23    4]
 [   5   67    8]
 [   9 1011   12]
 [  13 1415   16]]


# Question 8

In [48]:
sum_first_row = np.sum(x[0, :])
print(sum_first_row)

10


In [49]:
std_second_column = np.std(x[:, 1])
print(std_second_column)

4.47213595499958


In [53]:
element_first_row_second_column = x[0, 1]
print(element_first_row_second_column)

2


# Question 9

In [55]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])